name: Conditions workflow
on: push
jobs:
  skip-or-run:
    if: ${{ github.actor == 'octocat' }}  # octocatアカウント以外による実行はスキップ
    runs-on: ubuntu-latest
    steps:
      - run: echo "Pushed by octocat"